openapi: 3.1.0
info:
  title: Niat Memory
  version: 1.0.0
  description: API for storing and retrieving memory entries in Niat.

servers:
  - url: https://14b2-85-227-131-220.ngrok-free.app
    description: Ngrok tunnel to local Flask server

paths:
  /chunks:
    get:
      operationId: listChunks
      summary: List all memory chunks
      responses:
        '200':
          description: A list of chunk filenames
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      operationId: createChunk
      summary: Create a new memory chunk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                content:
                  type: string
              required:
                - filename
                - content
      responses:
        '200':
          description: Chunk successfully created

  /chunks/{filename}:
    get:
      operationId: getChunk
      summary: Retrieve memory chunk content
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The content of the chunk
          content:
            text/plain:
              schema:
                type: string
    put:
      operationId: updateChunk
      summary: Update memory chunk content
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
                - content
      responses:
        '200':
          description: Chunk updated
