openapi: "3.1.0"
info:
  version: 1.0.0
  title: Niat Memory API
  description: API för att lagra och hämta minnesdata i Niat.
  license:
    name: MIT
servers:
  - url: https://e102-85-227-131-220.ngrok-free.app
paths:
  /memory:
    get:
      summary: Hämta minne
      operationId: getMemory
      tags:
        - memory
      responses:
        '200':
          description: Nuvarande lagrat minne
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MemoryResponse"
    post:
      summary: Spara nytt minne
      operationId: storeMemory
      tags:
        - memory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MemoryRequest"
      responses:
        '200':
          description: Minnet sparades
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MemoryResponse"
components:
  schemas:
    MemoryRequest:
      type: object
      required:
        - memory
      properties:
        memory:
          type: string
    MemoryResponse:
      type: object
      properties:
        status:
          type: string
        data:
          type: string
