openapi: 3.1.0
info:
  title: Niat Memory
  version: 1.0.0
  description: API for storing and retrieving memory entries in Niat.
servers:
  - url: https://975f-85-227-131-220.ngrok-free.app
    description: Niat live tunnel via ngrok
paths:
  /chunks:
    get:
      operationId: listChunks
      summary: List all chunks
      responses:
        '200':
          description: A list of chunk filenames
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      operationId: createChunk
      summary: Create a new chunk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                content:
                  type: string
              required:
                - filename
                - content
      responses:
        '200':
          description: Chunk created
  /chunks/{filename}:
    put:
      operationId: updateChunk
      summary: Update an existing chunk
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
                - content
      responses:
        '200':
          description: Chunk updated
    get:
      operationId: getChunk
      summary: Get chunk content
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Chunk content
          content:
            text/plain:
              schema:
                type: string
