openapi: "3.1.0"
info:
  title: Niat Memory API
  version: "1.0.0"
  description: API for storing and retrieving memory entries in Niat.

servers:
  - url: "https://e102-85-227-131-220.ngrok-free.app"
    description: Niat temporary ngrok server

paths:
  /memory:
    get:
      operationId: getMemory
      summary: Get stored memory
      description: Retrieves the current stored memory from the service.
      responses:
        '200':
          description: Memory retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  memory:
                    type: string
    post:
      operationId: storeMemory
      summary: Store new memory
      description: Stores a new memory string into the service.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memory:
                  type: string
              required:
                - memory
      responses:
        '200':
          description: Memory stored successfully
