openapi: 3.1.3
info:
  title: Niat Memory
  version: 1.0.0
  description: API for storing and retrieving memory entries in Niat.
servers:
  - url: https://975f-85-227-131-220.ngrok-free.app
    description: Niat live tunnel via ngrok

paths:
  /chunks:
    get:
      operationId: listChunks
      summary: List all chunks
      description: Returns a list of all chunk filenames.
      responses:
        '200':
          description: A list of filenames
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      operationId: createChunk
      summary: Create a new memory chunk
      description: Create a new text chunk file in the memory store.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                content:
                  type: string
              required:
                - filename
                - content
      responses:
        '200':
          description: The chunk was successfully created.

  /chunks/{filename}:
    get:
      operationId: getChunk
      summary: Retrieve a chunk
      description: Get the content of a specific chunk by filename.
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The chunk content
          content:
            text/plain:
              schema:
                type: string

    put:
      operationId: updateChunk
      summary: Update an existing chunk
      description: Replace the content of an existing chunk file.
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
                - content
      responses:
        '200':
          description: Chunk was updated
