openapi: 3.1.0
info:
  title: Niat Memory
  version: 1.0.0
  description: API for reading, creating, and updating memory chunks in Niat.

servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /chunks:
    get:
      summary: List all chunk files
      operationId: listChunks
      responses:
        '200':
          description: A list of chunk filenames
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    post:
      summary: Create a new chunk
      operationId: createChunk
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                content:
                  type: string
              required:
                - filename
                - content
      responses:
        '200':
          description: Chunk created successfully

  /chunks/{filename}:
    get:
      summary: Get the content of a chunk
      operationId: getChunk
      parameters:
        - in: path
          name: filename
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Chunk content
          content:
            text/plain:
              schema:
                type: string
        '404':
          description: Chunk not found

    put:
      summary: Update the content of a chunk
      operationId: updateChunk
      parameters:
        - in: path
          name: filename
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              required:
                - content
      responses:
        '200':
          description: Chunk updated successfully
        '404':
          description: Chunk not found
